### ISSUE TITLE
Is v2 ready?

### ISSUE THREAD

**Issue by mattjefferson** [Thomas-Smyth/Original-SquadJS#3]
I see that you have a Pull request for v2... Is it close to ready... Would like to test this out a little more on our server.

**Comment by Thomas-Smyth** [comment]
I haven't touched the project in a while as we stopped using it on my server, The Coalition, for various reasons. As far as I recall, everything works well, but I have yet to document it. It's very similar to V1, however, so feel free to start using the branch if you are happy to attempt it without documentation. The `index.js` file in the root is a good starting place.

I have been planning on continuing working on this for a week or two now, but I imagine that my changes are either going to come as a v3 or in a new repo. This is due to plans to make significant changes to simplify to the system (e.g. remove the Koa style middleware) as I don't think the complexity, despite making this tool extremely powerful, is required in most use cases or the plugins I currently want to implement for my own server. v3 will also bring chat streaming, which I have working now in my own RCON client.

**Comment by Thomas-Smyth** [comment]
Please see the new SquadJS repo for the new rewrite/latest version: https://github.com/Thomas-Smyth/SquadJS
